# Generated by Django 5.1 on 2024-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_datetime', models.DateTimeField()),
                ('payee', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('user_notes', models.TextField()),
            ],
            options={
                'ordering': ['transaction_datetime'],
            },
        ),
    ]
